### ISSUE TITLE
Export button not working

### ISSUE THREAD

**Issue by Rish-Bansal** [Rakambda/YTTracker#37]
Export to file button not working

**Comment by Zwero1** [comment]
^

**Comment by Rakambda** [comment]
For reference:
```
Error in event handler: TypeError: URL.createObjectURL is not a function
    at YTTDownloadObject (chrome-extension://knnlnielflnfhdohmihofhdelgahgjdb/js/YTTUtils.js:656:20)
    at messageListener (chrome-extension://knnlnielflnfhdohmihofhdelgahgjdb/service_worker.js:338:3)
```
